name: rural_classroom
description: Rural Classroom mobile app for teachers and students in rural colleges.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  hive: ^2.2.3
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: any
  file_picker: ^8.0.2
  cached_network_image: ^3.3.1
  flutter_downloader: ^1.11.5
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
